name: android_tv_pdf_viewer
description: A Flutter project for viewing PDFs on Android TV.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# SDK Environment
environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
# NO NEED TO USE PACKAGES FOR SHITTY THINGS

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0

# Flutter Configuration
flutter:
  uses-material-design: true

  # To add assets in the future, uncomment the section below and specify paths
  # assets:
  #   - assets/images/
  #   - assets/fonts/
